apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
