apiVersion: v1
kind: Service
metadata:
  name: {{ include "config.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.adminService.port }}
      targetPort: adminhttp
      protocol: TCP
      name: adminhttp
  selector:
    {{- include "config.selectorLabels" . | nindent 4 }}
