name = "vex-worker"

workers_dev = true

compatibility_date = "2022-06-20"
compatibility_flags = []

main = "src/index.ts"

kv_namespaces = [
    { binding = "FLAG", id = "62be3e219ec343e881e8383162d21601", preview_id = "b4381d8894c14f58b211ddff52d760e4" },
    { binding = "TOKEN", id = "b98a38f9e1204262a9dd7aaea37bcc51", preview_id = "ae6c718cea5f4454a5fa88c4a128963b" }
]

[vars]

[env.staging]
account_id = ""

[env.staging.vars]


[env.production]
account_id = ""

[env.production.vars]
